defmodule Prismatic.LLM.Impl.TestBackend do
  @moduledoc """
  Test backend implementation for the LLM system.

  This backend provides a simple test implementation that can be used for
  development, testing, and examples. It supports configurable responses
  and simulates various error conditions.

  ## Configuration

      %{
        backend_type: :test,
        responses: %{
          "prompt" => "response"  # Custom response mapping (optional)
        },
        simulate_errors: boolean(),  # Enable error simulation (optional)
        delay_ms: integer()          # Response delay in ms (optional)
      }

  ## Examples

      # Basic test backend
      {:ok, config} = Prismatic.LLM.Backend.create_config(:test, %{})
      {:ok, response} = Prismatic.LLM.Backend.generate_response(config, "Hello", %{})

      # Test backend with custom responses
      {:ok, config} = Prismatic.LLM.Backend.create_config(:test, %{
        responses: %{
          "hello" => "Hello! How can I help you today?",
          "error" => {:error, :test_error}
        }
      })
  """

  @behaviour Prismatic.LLM.Backend

  alias Prismatic.LLM.Backend

  @impl Backend
  def generate_response(config, prompt, context \\ %{}) do
    # Add configurable delay for testing
    if delay = config[:delay_ms] do
      :timer.sleep(delay)
    end

    # Check for custom responses first
    case get_custom_response(config, prompt) do
      {:ok, response} ->
        {:ok, response}
      {:error, reason} ->
        {:error, reason}
      :not_found ->
        # Generate default test response
        generate_default_response(prompt, context)
    end
  end

  @impl Backend
  def validate_config(config) do
    cond do
      not is_map(config) ->
        {:error, :invalid_config_format}

      config.backend_type != :test ->
        {:error, {:invalid_backend_type, config.backend_type}}

      true ->
        :ok
    end
  end

  @impl Backend
  def health_check(_config) do
    :ok
  end

  @impl Backend
  def get_model_info(_config) do
    {:ok, %{
      name: "test-model-v1",
      max_tokens: 4096,
      supports_streaming: false,
      cost_per_token: 0.0,
      provider: :test,
      capabilities: [:completion, :chat]
    }}
  end

  ## Private Implementation

  defp get_custom_response(config, prompt) do
    case config[:responses] do
      %{^prompt => response} when is_binary(response) ->
        {:ok, response}
      %{^prompt => {:error, reason}} ->
        {:error, reason}
      _ ->
        :not_found
    end
  end

  defp generate_default_response(prompt, context) do
    temperature = context[:temperature] || 0.7
    max_tokens = context[:max_tokens] || 1000

    response = """
    Test LLM Response for: "#{prompt}"

    This is a test response generated by the Test Backend. In a real implementation,
    this would be replaced by actual LLM API calls.

    Request Context:
    - Temperature: #{temperature}
    - Max Tokens: #{max_tokens}
    - User ID: #{context[:user_id] || "anonymous"}

    Generated at: #{DateTime.utc_now() |> DateTime.to_iso8601()}
    """

    {:ok, String.trim(response)}
  end
end
